---
identifier: CVE-2019-10223
package_slug: go/github.com/kubernetes/kube-state-metrics
title: Information Exposure
description: A security issue was discovered in the kube-state-metrics versions. By
  default, the kube-state-metrics metrics only expose metadata about Secrets. However,
  a combination of the default `kubectl` behavior and this new feature can cause the
  entire secret content to end up in metric labels thus inadvertently exposing the
  secret content in metrics.
date: '2019-11-29'
pubdate: '2019-11-05'
affected_range: ">=1.7.0 <=1.7.1"
fixed_versions:
- 1.7.2
affected_versions: All versions starting from 1.7.0 up to 1.7.1
_git_import_path: go/github.com/kubernetes/kube-state-metrics
not_impacted: All versions before 1.7.0, all versions after 1.7.1
solution: Upgrade to version 1.7.2 or above.
urls:
- https://nvd.nist.gov/vuln/detail/CVE-2019-10223
- https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2019-10223
cvss_v2: AV:N/AC:L/Au:S/C:P/I:N/A:N
uuid: 23dc9fbd-85ce-4a19-94ea-a1be0c2365ae
