---
identifier: CVE-2019-11244
package_slug: go/github.com/kubernetes/client-go
title: Information Exposure Through Caching
description: In Kubernetes, schema info is cached by `kubectl` in the location specified
  by `--cache-dir` (defaulting to `$HOME/.kube/http-cache`), written with world-writeable
  permissions (`rw-rw-rw-`). If `--cache-dir` is specified and pointed at a different
  location accessible to other users/groups, the written files may be modified by
  other users/groups and disrupt the kubectl invocation.
date: '2019-05-09'
pubdate: '2019-04-22'
affected_range: ">=1.8.0 <=1.14.1"
fixed_versions:
- 1.14.2
affected_versions: All versions starting from 1.8.0 up to 1.14.1
_git_import_path: go/github.com/kubernetes/client-go/discovery/cached/disk
not_impacted: All versions before 1.8.0, all versions after 1.14.1
solution: Upgrade to version 1.14.2 or above.
urls:
- https://nvd.nist.gov/vuln/detail/CVE-2019-11244
- http://www.securityfocus.com/bid/108064
cvss_v2: AV:L/AC:M/Au:N/C:N/I:P/A:N
uuid: 9a595ab3-664d-49d5-9a7b-2e0e7254f849
