---
identifier: CVE-2019-1002101
package_slug: go/github.com/kubernetes/client-go
title: Improper Link Resolution Before File Access
description: The kubectl `cp` command allows copying files between containers and
  the user machine. To copy files from a container, Kubernetes creates a tar inside
  the container, copies it over the network, and kubectl unpacks it on the user's
  machine. If the tar binary in the container is malicious, it could run any code
  and output unexpected, malicious results. An attacker could use this to write files
  to any path on the user's machine when kubectl `cp` is called, limited only by the
  system permissions of the local user. The `untar` function can both create and follow
  symbolic links.
date: '2019-10-22'
pubdate: '2019-04-01'
affected_range: ">=1.11.0 <1.11.9||>=1.12.0 <1.12.7||>=1.13.0 <1.13.5||==1.14.0"
fixed_versions:
- 1.14.1
affected_versions: All versions starting from 1.11.0 before 1.11.9, all versions starting
  from 1.12.0 before 1.12.7, all versions starting from 1.13.0 before 1.13.5, version
  1.14.0
_git_import_path: go/github.com/kubernetes/client-go/discovery/cached/disk
not_impacted: All versions before 1.11.0, all versions starting from 1.11.9 before
  1.12.0, all versions starting from 1.12.7 before 1.13.0, all versions starting from
  1.13.5 before 1.14.0, all versions after 1.14.0
solution: Upgrade to version kubernetes-1.16.2 or above.
urls:
- https://nvd.nist.gov/vuln/detail/CVE-2019-1002101
- http://www.securityfocus.com/bid/107652
cvss_v2: AV:N/AC:M/Au:N/C:N/I:P/A:P
uuid: 5a90e146-6740-4f3d-b256-f2e583c12822
